node{
    stage('SCM Checkout'){
        git url:'https://github.com/amroarafat84/oracle-vm-demo.git'
    }
    stage('MVN Package'){
        def mvnHome = tool name: 'maven', type: 'maven'
        def mvnCMD = "${mvnHome}/bin/mvn"
        sh "cd demo && ${mvnCMD } clean package"
    }
    stage('Docker run'){
        sh "docker build --tag=message-server:latest demo/."
        sh "docker container rm -f message-server"
        sh "docker run -d -p9999:9999 --name message-server message-server:latest"
        sh "docker image prune -f"
    }
    stage("Clean workspace"){
        cleanWs()
    }
}