node{
    stage('SCM Checkout'){
        git url:'https://github.com/amroarafat84/oracle-vm-demo.git'
    }
    stage('MVN Package'){
        def mvnHome = tool name: 'maven', type: 'maven'
        def mvnCMD = "${mvnHome}/bin/mvn"
        sh "cd demo && ${mvnCMD } clean package"
    }
    stage('Docker run'){
        sh "docker build --tag=message-server:latest demo/."
        sh "docker run  -p9999:9999 message-server:latest"
    }
}